<?php
$arr_worldcup = array(
 'KIMPEMBE'=>"MoyUcwO",
 'ALDERWEIRELD'=>"YqoqxR4",
 'BOATENG'=>"Xc3Aj0A",
 'BONUCCI'=>"XnPY8Dl",
 'CHIELLINI'=>"hjC8glZ",
 'DE_LIGT'=>"8Xbc5ee",
 'GODIN'=>"nhrSRjz",
 'VERTONGHEN'=>"hNte4i5",

 'GOMEZ'=>"nEDeySE",
 'HUMMELS'=>"WpecmqN",
 'KOMPANY'=>"mxEdXLN",
 'KOULIBALY'=>"mxfiG6j",
 'STONES'=>"PQTRtZH",
 'LOVREN'=>"j0im63A",
 'LUIZ'=>"CDBVlkm",
 'MAGUIRE'=>"0dgsuJa",

 'MANOLAS'=>"iE65ZA3",
 'MIRANDA'=>"RMeQjmo",
 'MUSTAFI'=>"GOUlDAC",
 'PIQUE'=>"Pwj4JnM",
 'RAMOS'=>"tLt2O1P",
 'RUDIGER'=>"CgOKm6b",
 'SULE'=>"NACTFSw",
 'VARANE'=>"RBgLWsq",

 'SKRINIAR'=>"5jjFAjK",
 'VAN_DIJK'=>"AT3BvAH",
 'VIDA'=>"rPNOeEB",
 'SOKRATIS'=>"eTnhvOK",
 'T.SILVA'=>"WAivNSC",
 'UMTITI'=>"72BI1zZ",
 'LAPORTE'=>"WCQMaPi",
 'SMALLING'=>"tROFV69"
);

$arr_threemid = array(
  'Savic'=>"mxvsPpx",
  'Silva'=>"b76nkEx",
  'Kroos'=>"3DJBlWz",
  'Vidal'=>"HKiqQAA",
  'Pjanic'=>"vVg7kKw",
  'Pogba'=>"fD4fsIy",
  'Rakitic'=>"kYoTRxg",
  'Ozil'=>"qxZlBVG",
  'Matuidi'=>"PffGETw",

  'Busquets'=>"abJ2fCf",
  'Alli'=>"Toga0ta",
  'Casemiro'=>"QcD0nux",
  'Modric'=>"ZGrETbD",
  'James'=>"665PBeR",
  'Jorginho'=>"5jMkD50",
  'Kante'=>"A51UKpB",
  'DeBruyne'=>"VGCxUx7",
  'Eriksen'=>"lKGaMN2"
);

  $arr_myhero = array(
  'Thierry_Henry'=>"n1PZoJF",
  'Zinedine_Zidane'=>"rJ1TIrP",
  'Alessandro_Del_Piero'=>"9vyhZNO",
  'David_Villa'=>"RsXLtNv",
  'Luis_Suarez'=>"ZxuNeZf",
  'Luka_Modric'=>"kLmGL2q",

  'Fernando_Torres'=>"qehFYRa",
  'Lionel_Messi'=>"RLZcvGO",
  'Rivaldo'=>"rkB1s0m",
  'Raul_Gonzalez'=>"Cc30XEs",
  'Edinson_Cavani'=>"tm2J0QT",
  'Pavel_Nedved'=>"XegfwlZ",
  'Radamel_Falcao'=>"DAJpFm4",

  'Marco_Reus'=>"t2EubE4",
  'Robin_van_Persie'=>"b6rE3LF",
  'Andriy_Shevchenko'=>"J4FSrgV",
  'Robert_Pires'=>"0XmaLFF",
  'Henrik_Larsson'=>"VVSuk1S",
  'Ronaldo'=>"qznwDzl",
  'Esteban_Cambiasso'=>"YqG1Xb7",

  'Philipp_Lahm'=>"JpGGkwq",
  'Ronald_Koeman'=>"eruCwwt",
  'Fernando_Redondo'=>"2bEgYEj",
  'Antonio_Valencia'=>"VQFKaQk",
  'Arturo_Vidal'=>"hYaWa2N",
  'Dani_Alves'=>"ylQcyrT",
  'Willy_Sagnol'=>"e45cwLM",

  'MAICON'=>"5rsSjUR",
  'Sergio_Busquets'=>"vMctnxq",
  'Ashley_Cole'=>"GoKPa3X",
  'Gary_Neville'=>"cMdfu7Y",
  'Cafu'=>"KR3ozIz",
  'Giovanni_van_Bronckhorst'=>"uRd1fSk",
  'Franco_Baresi'=>"NSpbdsU",

  'Fernando_Hierro'=>"ANxt4Lo",
  'Eric_Abidal'=>"oolexMY",
  'Patrice_Evra'=>"jcqXaG4",
  'Christian_Panucci'=>"aiTZakr",
  'Kyle_Walker'=>"B6IBoQG",
  'Frank_Lampard'=>"fv5KfEj",
  'Steven_Gerrard'=>"eZDmfK6",

  'Didier_Drogba'=>"wsvLm5g",
  'Francesco_Totti'=>"1G6hohy",
  'Carlos_Tevez'=>"ejJcV2s",
  'Mario_Mandzukic'=>"d5CJgLD",
  'Wayne_Rooney'=>"oRX3UPi",
  'Robert_Lewandowski'=>"k49AQ2m",
  'Diego_Millito'=>"IPtupwo",

  'Yaya_Toure'=>"FBFLsxF",
  'Alan_Shearer'=>"d9LTlM2",
  'Michael_Ballack'=>"2MyBUTe",
  'Bastian_Schweinsteiger'=>"jg7lslI",
  'Miroslav_Klose'=>"Kr3QKn1",
  'Hulk'=>"uPInnSb",
  'Zlatan_Ibarahimovic'=>"9CS6LKB",

  'Gabriel_Batistuta'=>"8pukfRU",
  'Samuel_Eto\'o'=>"a2hXEj2",
  'Diego_Costa'=>"V7vJVjw",
  'Cristiano_Ronaldo'=>"42C2NeO",
  'Daniele_De_Rossi'=>"e0q9ZdX",
  'Rio_Ferdinand'=>"9Ur5itX",

  'Gerard_Pique'=>"AwNIz9l",
  'Giorgio_Chiellini'=>"evMUUX0",
  'Michael_Essien'=>"w2SYsG9",
  'Javi_Martinez'=>"ubVwNEW",
  'Javier_Zanetti'=>"1ilCLom",
  'Jerome_Boateng'=>"Xc3Aj0A",
  'Thiago_Silva'=>"lLyRLdt",

  'Mats_Hummels'=>"Hvb6IEK",
  'Carles_Puyol'=>"texiSaI",
  'Patrick_Vieira'=>"ARZeT9a",
  'Roy_Keane'=>"1vXN3Gt",
  'Sergio_Ramos'=>"NGetXpk",
  'Paolo_Maldini'=>"CVmizs4",
  'David_Luiz'=>"vCZOsmT",
  'Alessandro_Nesta'=>"mgKloRa",

  'Edgar_Davids'=>"tOie1P7",
  'Frank_Rijkaard'=>"M11eBz2",
  'Lucio'=>"JwHOmDQ",
  'Xavi_hernandez'=>"y5h6FKX"
);
?>
